name: Terraform.CICD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform_Init
        run: terraform init # Initialize Terraform
        working-directory: ./Terraform
  

     # - name: Terraform_Format_Check
      #  run: terraform fmt -check # Check formatting
  

      - name: Terraform_Validate
        run: terraform validate # Validate configuration
        working-directory: ./Terraform
        

      - name: Terraform_Destroy
        run: terraform destroy -auto-approve
        working-directory: ./Terraform
        

      - name: Terraform_Plan
        run: terraform plan -out=tfplan # Create execution plan
        working-directory: ./Terraform
      
      - name: Terraform Apply 
        run: terraform apply -auto-approve tfplan
        working-directory: ./Terraform
